stages:
  - lint-helm-chart

image:
  name: alpine/helm:3.2.1
  entrypoint: ["/bin/sh", "-c"]
variables:
  HELM_EXPERIMENTAL_OCI: 1
lint-helm:
  stage: lint-helm-chart
  script:
    - helm lint ${CHART_NAME}
    - helm lint ${CHART_NAME} -f ${CHART_NAME}/values-test.yaml