stages:
  - lint-helm-chart
  - update_chart_version
  - publish-helm-chart

variables:
  CHART_NAME: "application"
  HELM_VERSION: "3.16"
  HELM_EXPERIMENTAL_OCI: 1
  CHART_PACKAGE_DIR: "charts"
  GITLAB_REGISTRY_URL: "${CI_SERVER_HOST}/api/v4/projects/${CI_PROJECT_ID}/packages/helm"  # GitLab Package Registry URL

lint-helm:
  image: 
    name: alpine/helm:${HELM_VERSION}
    entrypoint: ["/bin/sh", "-c"]
  stage: lint-helm-chart
  script:
    - helm lint ${CHART_NAME}
  only:
    - tags

update_chart_version:
  stage: update_chart_version
  script:
    # Remove the leading 'v' from the Git tag (if exists)
    - CHART_VERSION=${CI_COMMIT_TAG#v}
    
    # Update the version in Chart.yaml with the current Git tag
    - sed -i "s/^version:.*/version: ${CHART_VERSION}/" ${CHART_NAME}/Chart.yaml
    
    # Optional: Verify the version update
    - cat ${CHART_NAME}/Chart.yaml
  only:
    - tags

publish-helm:
  image: 
    name: alpine/helm:${HELM_VERSION}
    entrypoint: ["/bin/sh", "-c"]
  stage: publish-helm-chart
  script:
    - helm --help
    - echo "$CI_REGISTRY_PASSWORD" | helm registry login $CI_REGISTRY -u $CI_REGISTRY_USER --password-stdin
    - helm package ${CHART_NAME} --destination ${CHART_PACKAGE_DIR}
    - helm cm-push ${CHART_PACKAGE_DIR}/${CHART_NAME}-${CHART_VERSION}.tgz oci://${GITLAB_REGISTRY_URL}
  only:
    - tags
