stages:
  - lint-helm-chart
  - publish-helm-chart

variables:
  CHART_NAME: "application"
  HELM_VERSION: "3.16"
  HELM_EXPERIMENTAL_OCI: 1
  CHART_PACKAGE_DIR: "charts"
  GITLAB_REGISTRY_URL: "${CI_SERVER_HOST}/api/v4/projects/${CI_PROJECT_ID}/packages/helm"  # GitLab Package Registry URL

lint-helm:
  image: 
    name: alpine/helm:${HELM_VERSION}
    entrypoint: ["/bin/sh", "-c"]
  stage: lint-helm-chart
  script:
    - helm lint ${CHART_NAME}

publish-helm:
  image: 
    name: alpine/helm:${HELM_VERSION}
    entrypoint: ["/bin/sh", "-c"]
  stage: publish-helm-chart
  script:
    - helm --help
    - echo "$CI_REGISTRY_PASSWORD" | helm registry login $CI_REGISTRY -u $CI_REGISTRY_USER --password-stdin
    - helm package ${CHART_NAME} --destination ${CHART_PACKAGE_DIR}