stages:
  - lint-helm-chart
  - update_chart_version
  - publish-helm-chart

variables:
  CHART_NAME: "application"
  HELM_VERSION: "3.16"
  HELM_EXPERIMENTAL_OCI: 1
  CHART_PACKAGE_DIR: "charts"
  GITLAB_REGISTRY_URL: "${CI_SERVER_HOST}/api/v4/projects/${CI_PROJECT_ID}/packages/helm/stable"  # GitLab Package Registry URL
  CI_COMMIT_TAG: "v2.2.2"
lint-helm:
  image: 
    name: alpine/helm:${HELM_VERSION}
    entrypoint: ["/bin/sh", "-c"]
  stage: lint-helm-chart
  script:
    - helm lint ${CHART_NAME}
  # only:
  #   - tags

update_chart_version:
  stage: update_chart_version
  script:
    - CHART_VERSION=${CI_COMMIT_TAG#v}
    - echo $CHART_VERSION ${CHART_VERSION}
    - cat ${CHART_NAME}/Chart.yaml
  # only:
  #   - tags

publish-helm:
  image: 
    name: alpine/helm:${HELM_VERSION}
    entrypoint: ["/bin/sh", "-c"]
  stage: publish-helm-chart
  before_script:
    - helm plugin install https://github.com/chartmuseum/helm-push
    - helm repo add --username gitlab-ci-token --password ${CI_JOB_TOKEN} ${CI_PROJECT_NAME} ${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/helm/stable
  script:
    - helm --help
    - helm package ${CHART_NAME} --destination ${CHART_PACKAGE_DIR}
    - echo ${GITLAB_REGISTRY_URL}
    - echo ${CI_PROJECT_NAME} ${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/helm/stable
    # - helm push ${CHART_PACKAGE_DIR}/${CHART_NAME}-4.2.6.tgz oci://${GITLAB_REGISTRY_URL}
    - helm cm-push ${CHART_PACKAGE_DIR}/${CHART_NAME}-4.2.6.tgz ${CI_PROJECT_NAME}
  # only:
  #   - tags
