stages:
  - lint-helm-chart
  - publish-helm-chart

variables:
  CHART_NAME: "application"
  HELM_VERSION: "3.16"
  HELM_EXPERIMENTAL_OCI: 1

lint-helm:
  image: 
    name: alpine/helm:${HELM_VERSION}
    entrypoint: ["/bin/sh", "-c"]
  stage: lint-helm-chart
  script:
    - helm lint ${CHART_NAME}

publish-helm:
  image: 
    name: alpine/helm:${HELM_VERSION}
    entrypoint: ["/bin/sh", "-c"]
  stage: publish-helm-chart
  script:
    - helm lint ${CHART_NAME}
    - echo "Helm chart published"
