stages:
  - build
  - test

variables:
  CHART_NAME: "application"
  KUBECONFIG: "$CI_PROJECT_DIR/.kubeconfig.yaml"

before_script:
  - export KUBECONFIG=$KUBECONFIG

build:
  stage: build
  script:
    - |
      if [[ "$(echo $CI_COMMIT_MESSAGE)" != *"[skip-ci]"* ]]; then
        # Check out code (Already done in GitLab automatically)
        
        # Set up Helm
        curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
        helm version --short

        # Lint
        helm lint ${CHART_NAME}
        helm lint ${CHART_NAME} -f ${CHART_NAME}/values-test.yaml
