name: Push Helm Chart

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'
      - 'LICENSE'

env:
  CHART_NAME: "application"

jobs:
  helm-dry-run:
    name: Helm Dry Run
    runs-on: ubuntu-latest
    
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      # Set Up Helm
      - name: Set up Helm
        uses: azure/setup-helm@v4
        with:
          version: v3.8.2

      # Lint Helm Chart
      - name: Helm Lint
        run: |
          helm lint ${CHART_NAME}
          helm lint ${CHART_NAME} -f ${CHART_NAME}/values-test.yaml

  push-changes:
    name: Push Changes Helm Chart
    runs-on: ubuntu-latest
    needs: helm-dry-run
    
    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          persist-credentials: false # ใช้ personal token แทน GITHUB_TOKEN
          fetch-depth: 0 # เพื่อป้องกันการล้มเหลวในการ push refs ไปยัง repo

      # Configure Git to use token for authentication
      - name: Configure Git to use token
        run: |
          git config --global url."https://${{ github.actor }}:${{ secrets.PIPELINE }}@github.com/".insteadOf "https://github.com/"

      # Generate tag for chart without "v" prefix
      - name: Generate Tag
        id: generate_tag
        uses: anothrNick/github-tag-action@1.70.0
        env:
          GITHUB_TOKEN: ${{ secrets.PIPELINE }}
        with:
          WITH_V: false
          DEFAULT_BUMP: patch
          DRY_RUN: false

      # Update Chart Version
      - name: Update Chart Version
        run: |
          sed -i "s/^version:.*/version: ${{ steps.generate_tag.outputs.new_tag }}/" ${CHART_NAME}/Chart.yaml

      # Set Up Helm
      - name: Set up Helm
        uses: azure/setup-helm@v4
        with:
          version: v3.8.2

      # Package Helm Chart
      - name: Package Helm Chart
        run: |
          helm package ${CHART_NAME}

      # Push Helm Chart to GitHub Pages
      - name: Publish Helm Chart
        uses: helm/chart-releaser-action@v1.4.0
        with:
          version: v1.4.0
          charts_dir: application
          owner: ${{ github.actor }}
          repo: ${{ github.repository }}
          token: ${{ secrets.PIPELINE }}

        